AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false